apiVersion: 1
providers:
- name: 'default-provider'
  orgId: 1
  folder: dashboards
  folderUid: ''
  type: file
  disableDeletion: false
  editable: true
  updateIntervalSeconds: 10
  options:
    path: /etc/grafana/dashboards
    foldersFromFilesStructure: true